package com.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class SolutionTest {
    
    //This is the test, please do not edit this file. The correct file is under main->java->com->example->Solution.java
    @Test public void test0(){
        int[] deck = {1,2,3,4,5};
        int[] sampleResult = {1,3,5,4,2};
        Solution queue = new Solution(20, deck);
        int[] result = queue.result();
        assertArrayEquals(result,sampleResult);
    }

    @Test public void test1(){
        int[] deck = {1};
        int[] sampleResult = {1};
        Solution queue = new Solution(20, deck);
        int[] result = queue.result();
        assertArrayEquals(result,sampleResult);
    }

    @Test public void test2(){
        int[] deck = {};
        int[] sampleResult = {};
        Solution queue = new Solution(20, deck);
        int[] result = queue.result();
        assertArrayEquals(result,sampleResult);
    }

    @Test public void test3(){
        int[] deck = {1,2,3,4,5,6,7};
        int[] sampleResult = {1,3,5,7,4,2,6};
        Solution queue = new Solution(20, deck);
        int[] result = queue.result();
        assertArrayEquals(result,sampleResult);
    }

    @Test public void test4(){
        int[] deck = {1,2,3,4,5,6,7};
        int[] sampleResult = {1,3,5,7,4,2,6};
        Solution queue = new Solution(10, deck);
        int[] result = queue.result();
        assertArrayEquals(result,sampleResult);
    }

    @Test public void test5(){
        int[] deck = {1,2,3,4,5,6,7};
        int[] sampleResult = {1,3,5,7,4,2,6};
        Solution queue = new Solution(7, deck);
        int[] result = queue.result();
        assertArrayEquals(result,sampleResult);
    }

    @Test public void test6(){
        int[] deck = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18};
        int[] sampleResult = {1,3,5,7,9,11,13,15,17,2,6,10,14,18,8,16,12,4};
        Solution queue = new Solution(20, deck);
        int[] result = queue.result();
        assertArrayEquals(result,sampleResult);
    }
}
